name: "Terraform Tests"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: "26fa681b-266b-4a85-b7f0-d0b40312d4e0"
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  TF_LOG: DEBUG
  PYTHONUNBUFFERED: 1

jobs:
  validate:
    name: "Validate Terraform"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

  test:
    name: "Run Tests"
    needs: validate
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v3

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
          pip install azure-cli

      - name: Verify Azure Login
        run: |
          echo "Current Azure Account:"
          az account show
          echo "Setting Azure Subscription..."
          az account set --subscription="26fa681b-266b-4a85-b7f0-d0b40312d4e0"

      - name: Test Core Modules
        run: python tests/infrastructure_test.py --ci --test-type modules --output test_results_modules.json || {
            echo "=== Core Modules Test Failed ==="
            cat test_results_modules.json || true
            terraform show || true
            exit 1
          }

      - name: Test Backend
        run: python tests/infrastructure_test.py --ci --test-type backend --output test_results_backend.json || {
            echo "=== Backend Test Failed ==="
            cat test_results_backend.json || true
            terraform show || true
            exit 1
          }
      
      - name: Test All Environments
        run: python tests/infrastructure_test.py --ci --test-type all-env --output test_results_allenv.json || {
            echo "=== All Environments Test Failed ==="
            cat test_results_allenv.json || true
            terraform show || true
            exit 1
          }

      - name: Test Dev
        run: python tests/infrastructure_test.py --ci --test-type dev --output test_results_dev.json || {
            echo "=== Dev Environment Test Failed ==="
            cat test_results_dev.json || true
            cd environments/dev || true
            terraform init -backend=false
            terraform plan || true
            terraform show || true
            echo "=== Terraform Logs ==="
            find . -name "*.log" -type f -exec cat {} \;
            exit 1
          }

      - name: Test Staging
        run: python tests/infrastructure_test.py --ci --test-type staging --output test_results_staging.json || {
            echo "=== Staging Environment Test Failed ==="
            cat test_results_staging.json || true
            cd environments/staging || true
            terraform init -backend=false
            terraform plan || true
            terraform show || true
            echo "=== Terraform Logs ==="
            find . -name "*.log" -type f -exec cat {} \;
            exit 1
          }

      - name: Test Production
        run: python tests/infrastructure_test.py --ci --test-type prod --output test_results_prod.json || {
            echo "=== Production Environment Test Failed ==="
            cat test_results_prod.json || true
            cd environments/prod || true
            terraform init -backend=false
            terraform plan || true
            terraform show || true
            echo "=== Terraform Logs ==="
            find . -name "*.log" -type f -exec cat {} \;
            exit 1
          }

      - name: Upload Test Results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: failed-test-results
          path: |
            **/*.json
            **/logs/
            **/*.log

  deploy:
    name: "Deploy Infrastructure"
    needs: [validate, test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve